In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [8]:
df = pd.read_csv(r"C:\Users\ryana\Downloads\DataSet\Credit Card\application_record.csv")
df1 = pd.read_csv(r"C:\Users\ryana\Downloads\DataSet\Credit Card\credit_record.csv")
pd.set_option("display.max_columns", None)

In [3]:
df

,ID,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,DAYS_BIRTH,DAYS_EMPLOYED,FLAG_MOBIL,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS
0,5008804,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2.0
1,5008805,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2.0
2,5008806,M,Y,Y,0,112500.0,Working,Secondary / secondary special,Married,House / apartment,-21474,-1134,1,0,0,0,Security staff,2.0
3,5008808,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,-19110,-3051,1,0,1,1,Sales staff,1.0
4,5008809,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,-19110,-3051,1,0,1,1,Sales staff,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
438552,6840104,M,N,Y,0,135000.0,Pensioner,Secondary / secondary special,Separated,House / apartment,-22717,365243,1,0,0,0,NaN,1.0
438553,6840222,F,N,N,0,103500.0,Working,Secondary / secondary special,Single / not married,House / apartment,-15939,-3007,1,0,0,0,Laborers,1.0
438554,6841878,F,N,N,0,54000.0,Commercial associate,Higher education,Single / not married,With parents,-8169,-372,1,1,0,0,Sales staff,1.0
438555,6842765,F,N,Y,0,72000.0,Pensioner,Secondary / secondary special,Married,House / apartment,-21673,365243,1,0,0,0,NaN,2.0
438556,6842885,F,N,Y,0,121500.0,Working,Secondary / secondary special,Married,House / apartment,-18858,-1201,1,0,1,0,Sales staff,2.0

In [4]:
df1.sample(5)

             ID  MONTHS_BALANCE STATUS
268625  5024035             -11      C
542007  5065544             -22      0
597039  5069392             -25      0
416080  5048619              -8      0
638952  5089338              -1      0

### Merge Data by ID with Inner Method

In [5]:
data = pd.merge(df, df1, on='ID', how='inner')

In [7]:
data.sample()

,ID,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,DAYS_BIRTH,DAYS_EMPLOYED,FLAG_MOBIL,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,MONTHS_BALANCE,STATUS
77002,5023389,M,Y,Y,2,157500.0,Commercial associate,Higher education,Married,House / apartment,-13536,-2092,1,0,0,0,Core staff,4.0,-5,0

In [10]:
data.shape

(777715, 20)

In [11]:
data.isnull().sum()

ID                          0
CODE_GENDER                 0
FLAG_OWN_CAR                0
FLAG_OWN_REALTY             0
CNT_CHILDREN                0
AMT_INCOME_TOTAL            0
NAME_INCOME_TYPE            0
NAME_EDUCATION_TYPE         0
NAME_FAMILY_STATUS          0
NAME_HOUSING_TYPE           0
DAYS_BIRTH                  0
DAYS_EMPLOYED               0
FLAG_MOBIL                  0
FLAG_WORK_PHONE             0
FLAG_PHONE                  0
FLAG_EMAIL                  0
OCCUPATION_TYPE        240048
CNT_FAM_MEMBERS             0
MONTHS_BALANCE              0
STATUS                      0
dtype: int64

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 777715 entries, 0 to 777714
Data columns (total 20 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   ID                   777715 non-null  int64
 1   CODE_GENDER          777715 non-null  object
 2   FLAG_OWN_CAR         777715 non-null  object
 3   FLAG_OWN_REALTY      777715 non-null  object
 4   CNT_CHILDREN         777715 non-null  int64
 5   AMT_INCOME_TOTAL     777715 non-null  float64
 6   NAME_INCOME_TYPE     777715 non-null  object
 7   NAME_EDUCATION_TYPE  777715 non-null  object
 8   NAME_FAMILY_STATUS   777715 non-null  object
 9   NAME_HOUSING_TYPE    777715 non-null  object
 10  DAYS_BIRTH           777715 non-null  int64
 11  DAYS_EMPLOYED        777715 non-null  int64
 12  FLAG_MOBIL           777715 non-null  int64
 13  FLAG_WORK_PHONE      777715 non-null  int64
 14  FLAG_PHONE           777715 non-null  int64
 15  FLAG_EMAIL           777715 non-null  int64
 16  OCCUPATION_TYPE      537667 non-null  object
 17  CNT_FAM_MEMBERS      777715 non-null  float64
 18  MONTHS_BALANCE       777715 non-null  int64
 19  STATUS               777715 non-null  object
dtypes: float64(2), int64(9), object(9)
memory usage: 118.7+ MB

In [13]:
data.head()

,ID,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,DAYS_BIRTH,DAYS_EMPLOYED,FLAG_MOBIL,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,MONTHS_BALANCE,STATUS
0,5008804,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2.0,0,C
1,5008804,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2.0,-1,C
2,5008804,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2.0,-2,C
3,5008804,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2.0,-3,C
4,5008804,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2.0,-4,C

In [14]:
data.columns

Index(['ID', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN',
       'AMT_INCOME_TOTAL', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE',
       'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'DAYS_BIRTH',
       'DAYS_EMPLOYED', 'FLAG_MOBIL', 'FLAG_WORK_PHONE', 'FLAG_PHONE',
       'FLAG_EMAIL', 'OCCUPATION_TYPE', 'CNT_FAM_MEMBERS', 'MONTHS_BALANCE',
       'STATUS'],
      dtype='object')

In [29]:
cols_head=[
    'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN',
    'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE',
    'OCCUPATION_TYPE', 'STATUS'
]

for cols in cols_head:
    if cols in data.columns:
        print(f"Column {cols}:")
        print(data[cols].unique())
        print()
    else:
        print(f"Column {cols} is not in the DataFrame.\n")

Column CODE_GENDER:
['M' 'F']

Column FLAG_OWN_CAR:
['Y' 'N']

Column FLAG_OWN_REALTY:
['Y' 'N']

Column CNT_CHILDREN:
[ 0  1  3  2  4  5 14 19  7]

Column NAME_INCOME_TYPE:
['Working' 'Commercial associate' 'Pensioner' 'State servant' 'Student']

Column NAME_EDUCATION_TYPE:
['Higher education' 'Secondary / secondary special' 'Incomplete higher'
 'Lower secondary' 'Academic degree']

Column NAME_FAMILY_STATUS:
['Civil marriage' 'Married' 'Single / not married' 'Separated' 'Widow']

Column NAME_HOUSING_TYPE:
['Rented apartment' 'House / apartment' 'Municipal apartment'
 'With parents' 'Co-op apartment' 'Office apartment']

Column OCCUPATION_TYPE:
[nan 'Security staff' 'Sales staff' 'Accountants' 'Laborers' 'Managers'
 'Drivers' 'Core staff' 'High skill tech staff' 'Cleaning staff'
 'Private service staff' 'Cooking staff' 'Low-skill Laborers'
 'Medicine staff' 'Secretaries' 'Waiters/barmen staff' 'HR staff'
 'Realty agents' 'IT staff']

Column STATUS:
['C' '1' '0' 'X' '5' '4' '3' '2']

In [40]:
recent18 = df1[df1['MONTHS_BALANCE'] >= -18].copy()

In [41]:
recent18

              ID  MONTHS_BALANCE STATUS
0        5001711               0      X
1        5001711              -1      0
2        5001711              -2      0
3        5001711              -3      0
4        5001712               0      C
...          ...             ...    ...
1048559  5150487             -14      C
1048560  5150487             -15      C
1048561  5150487             -16      C
1048562  5150487             -17      C
1048563  5150487             -18      C

[571740 rows x 3 columns]

In [42]:
bad_status = ['2', '3', '4', '5']
recent18['bad_credit'] = recent18['STATUS'].isin(bad_status).astype(int)

In [50]:
recent18

              ID  MONTHS_BALANCE STATUS  bad_credit
0        5001711               0      X           0
1        5001711              -1      0           0
2        5001711              -2      0           0
3        5001711              -3      0           0
4        5001712               0      C           0
...          ...             ...    ...         ...
1048559  5150487             -14      C           0
1048560  5150487             -15      C           0
1048561  5150487             -16      C           0
1048562  5150487             -17      C           0
1048563  5150487             -18      C           0

[571740 rows x 4 columns]

In [53]:
recent18[recent18['STATUS'] == '3']

              ID  MONTHS_BALANCE STATUS  bad_credit
104474   5009524               0      3           1
108661   5009744              -7      3           1
108666   5009744             -12      3           1
108764   5009749              -3      3           1
108769   5009749              -8      3           1
...          ...             ...    ...         ...
1007604  5145919              -1      3           1
1014280  5146444              -2      3           1
1020098  5148602              -5      3           1
1025743  5148934             -13      3           1
1040956  5149834             -13      3           1

[125 rows x 4 columns]

In [54]:
labels_revised = recent18.groupby('ID')['bad_credit'].max().reset_index()
labels_revised.rename(columns={'bad_credit': 'TARGET'}, inplace=True)

In [55]:
labels_revised

            ID  TARGET
0      5001711       0
1      5001712       0
2      5001713       0
3      5001714       0
4      5001715       0
...        ...     ...
41071  5150482       0
41072  5150483       0
41073  5150484       0
41074  5150485       0
41075  5150487       0

[41076 rows x 2 columns]

In [56]:
data = df.merge(labels_revised, on='ID', how='inner')

In [57]:
data

,ID,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,DAYS_BIRTH,DAYS_EMPLOYED,FLAG_MOBIL,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,TARGET
0,5008804,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2.0,0
1,5008805,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2.0,0
2,5008806,M,Y,Y,0,112500.0,Working,Secondary / secondary special,Married,House / apartment,-21474,-1134,1,0,0,0,Security staff,2.0,0
3,5008808,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,-19110,-3051,1,0,1,1,Sales staff,1.0,0
4,5008810,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,-19110,-3051,1,0,1,1,Sales staff,1.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31543,5149828,M,Y,Y,0,315000.0,Working,Secondary / secondary special,Married,House / apartment,-17348,-2420,1,0,0,0,Managers,2.0,1
31544,5149834,F,N,Y,0,157500.0,Commercial associate,Higher education,Married,House / apartment,-12387,-1325,1,0,1,1,Medicine staff,2.0,1
31545,5149838,F,N,Y,0,157500.0,Pensioner,Higher education,Married,House / apartment,-12387,-1325,1,0,1,1,Medicine staff,2.0,1
31546,5150049,F,N,Y,0,283500.0,Working,Secondary / secondary special,Married,House / apartment,-17958,-655,1,0,0,0,Sales staff,2.0,1
31547,5150337,M,N,Y,0,112500.0,Working,Secondary / secondary special,Single / not married,Rented apartment,-9188,-1193,1,0,0,0,Laborers,1.0,1

### Train/Test Split

In [58]:
X = data.drop(['TARGET'], axis=1)
y = data['TARGET']

In [59]:
from sklearn.model_selection import train_test_split
        
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, test_size=0.2, random_state=42)

In [60]:
print(f"Proporsi TARGET (y_train):")
y_train.value_counts(normalize=True)

Proporsi TARGET (y_train):

TARGET
0    0.989619
1    0.010381
Name: proportion, dtype: float64

In [61]:
print(f"Data Size:")
print("X_train", X_train.shape)
print("X_test", X_test.shape)

Data Size:
X_train (25238, 18)
X_test (6310, 18)

In [63]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 25238 entries, 16837 to 19533
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   25238 non-null  int64
 1   CODE_GENDER          25238 non-null  object
 2   FLAG_OWN_CAR         25238 non-null  object
 3   FLAG_OWN_REALTY      25238 non-null  object
 4   CNT_CHILDREN         25238 non-null  int64
 5   AMT_INCOME_TOTAL     25238 non-null  float64
 6   NAME_INCOME_TYPE     25238 non-null  object
 7   NAME_EDUCATION_TYPE  25238 non-null  object
 8   NAME_FAMILY_STATUS   25238 non-null  object
 9   NAME_HOUSING_TYPE    25238 non-null  object
 10  DAYS_BIRTH           25238 non-null  int64
 11  DAYS_EMPLOYED        25238 non-null  int64
 12  FLAG_MOBIL           25238 non-null  int64
 13  FLAG_WORK_PHONE      25238 non-null  int64
 14  FLAG_PHONE           25238 non-null  int64
 15  FLAG_EMAIL           25238 non-null  int64
 16  OCCUPATION_TYPE      17542 non-null  object
 17  CNT_FAM_MEMBERS      25238 non-null  float64
dtypes: float64(2), int64(8), object(8)
memory usage: 3.7+ MB

In [77]:
X_train

,ID,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,DAYS_BIRTH,DAYS_EMPLOYED,FLAG_MOBIL,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,AGE_YEARS,YEARS_EMPLOYED
16837,5087572,F,N,Y,1,225000.0,Commercial associate,Higher education,Single / not married,House / apartment,-15926,-3327.0,1,0,0,0,Unknown,2.0,43,9.0
31407,5096664,M,Y,N,0,135000.0,Pensioner,Secondary / secondary special,Married,House / apartment,-14400,-1953.0,1,0,1,0,Unknown,2.0,39,5.0
4485,5026014,F,N,Y,0,81000.0,Working,Secondary / secondary special,Married,House / apartment,-19893,-5365.0,1,1,1,0,Unknown,2.0,54,14.0
25216,5117276,M,Y,Y,1,180000.0,Working,Higher education,Married,House / apartment,-14082,-1800.0,1,0,0,0,Managers,3.0,38,4.0
7718,5041141,F,N,Y,0,157500.0,State servant,Incomplete higher,Civil marriage,House / apartment,-10338,-795.0,1,0,0,0,Core staff,2.0,28,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7403,5038576,F,N,Y,0,112500.0,Pensioner,Secondary / secondary special,Married,House / apartment,-24327,-1953.0,1,0,0,0,Unknown,2.0,66,5.0
29896,5146325,F,N,Y,0,67500.0,Pensioner,Secondary / secondary special,Married,House / apartment,-23097,-1953.0,1,0,0,0,Unknown,2.0,63,5.0
8472,5044515,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Married,House / apartment,-15176,-7100.0,1,0,1,0,Managers,2.0,41,19.0
8433,5042310,F,N,Y,2,157500.0,State servant,Higher education,Married,House / apartment,-14395,-5300.0,1,0,0,0,Accountants,4.0,39,14.0
19533,5092357,F,N,N,0,121500.0,Commercial associate,Secondary / secondary special,Civil marriage,House / apartment,-21587,-5009.0,1,0,0,0,Laborers,2.0,59,13.0

In [65]:
X_train['DAYS_EMPLOYED'] = X_train['DAYS_EMPLOYED'].replace(365243, np.nan)
X_test['DAYS_EMPLOYED'] = X_test['DAYS_EMPLOYED'].replace(365243, np.nan)

In [67]:
median_days_emp = X_train['DAYS_EMPLOYED'].median()
X_train['DAYS_EMPLOYED'] = X_train['DAYS_EMPLOYED'].fillna(median_days_emp)
X_test['DAYS_EMPLOYED'] = X_test['DAYS_EMPLOYED'].fillna(median_days_emp)

In [69]:
print(f"✅ Median dari DAYS_EMPLOYED (X_train): {median_days_emp}")

✅ Median dari DAYS_EMPLOYED (X_train): -1953.0

In [70]:
X_train['AGE_YEARS'] = (-X_train['DAYS_BIRTH']) // 365
X_test['AGE_YEARS'] = (-X_test['DAYS_BIRTH']) // 365

X_train['YEARS_EMPLOYED'] = (-X_train['DAYS_EMPLOYED']) // 365
X_test['YEARS_EMPLOYED'] = (-X_test['DAYS_EMPLOYED']) // 365

In [74]:
X_train.duplicated().sum()

np.int64(0)

In [78]:
X_train.isnull().sum()

ID                     0
CODE_GENDER            0
FLAG_OWN_CAR           0
FLAG_OWN_REALTY        0
CNT_CHILDREN           0
AMT_INCOME_TOTAL       0
NAME_INCOME_TYPE       0
NAME_EDUCATION_TYPE    0
NAME_FAMILY_STATUS     0
NAME_HOUSING_TYPE      0
DAYS_BIRTH             0
DAYS_EMPLOYED          0
FLAG_MOBIL             0
FLAG_WORK_PHONE        0
FLAG_PHONE             0
FLAG_EMAIL             0
OCCUPATION_TYPE        0
CNT_FAM_MEMBERS        0
AGE_YEARS              0
YEARS_EMPLOYED         0
dtype: int64

In [76]:
X_train['OCCUPATION_TYPE'].fillna("Unknown", inplace=True)
X_test['OCCUPATION_TYPE'].fillna("Unknown", inplace=True)

df.method({'OCCUPATION_TYPE': "Unknown"}, inplace=True)

C:\Users\ryana\AppData\Local\Temp\ipykernel_17280\2084391436.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_train['OCCUPATION_TYPE'].fillna("Unknown", inplace=True)
C:\Users\ryana\AppData\Local\Temp\ipykernel_17280\2084391436.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_test['OCCUPATION_TYPE'].fillna("Unknown", inplace=True)

In [80]:
categorical_train = X_train.select_dtypes(include='object').columns.tolist()
numerical_train = X_train.select_dtypes(include=['int64', 'float64']).columns.tolist()

In [81]:
drop_cols = ['DAYS_BIRTH', 'DAYS_EMPLOYED', 'FLAG_MOBIL', 'ID']
numerical_train = [col for col in numerical_train if col not in drop_cols]

In [82]:
# Drop kolom dari X_train dan X_test (inplace=False agar bisa dikontrol)
X_train = X_train.drop(columns=drop_cols, errors='ignore')
X_test = X_test.drop(columns=drop_cols, errors='ignore')
print(X_train.head())

      CODE_GENDER FLAG_OWN_CAR FLAG_OWN_REALTY  CNT_CHILDREN  \
16837           F            N               Y             1
31407           M            Y               N             0
4485            F            N               Y             0
25216           M            Y               Y             1
7718            F            N               Y             0

       AMT_INCOME_TOTAL      NAME_INCOME_TYPE            NAME_EDUCATION_TYPE  \
16837          225000.0  Commercial associate               Higher education
31407          135000.0             Pensioner  Secondary / secondary special
4485            81000.0               Working  Secondary / secondary special
25216          180000.0               Working               Higher education
7718           157500.0         State servant              Incomplete higher

         NAME_FAMILY_STATUS  NAME_HOUSING_TYPE  FLAG_WORK_PHONE  FLAG_PHONE  \
16837  Single / not married  House / apartment                0           0
31407               Married  House / apartment                0           1
4485                Married  House / apartment                1           1
25216               Married  House / apartment                0           0
7718         Civil marriage  House / apartment                0           0

       FLAG_EMAIL OCCUPATION_TYPE  CNT_FAM_MEMBERS  AGE_YEARS  YEARS_EMPLOYED
16837           0         Unknown              2.0         43             9.0
31407           0         Unknown              2.0         39             5.0
4485            0         Unknown              2.0         54            14.0
25216           0        Managers              3.0         38             4.0
7718            0      Core staff              2.0         28             2.0

In [83]:
import scipy.stats as stats

def check_plot(df_cs, column):
    plt.figure(figsize=(16, 4))

    plt.subplot(1, 3, 1)
    sns.histplot(df_cs[column], bins=30)
    plt.title(f'Histogram - {column}')

    plt.subplot(1, 3, 2)
    stats.probplot(df_cs[column], dist="norm", plot=plt)
    plt.ylabel('Variable quantiles')

    plt.subplot(1, 3, 3)
    sns.boxplot(y=df_cs[column])
    plt.title(f'Boxplot - {column}')

    st.pyplot(plt.gcf())
    plt.clf()

In [85]:
pilih_var_outlier = st.selectbox("Pilih variabel numerik untuk melihat outlier:", numerical_train)
check_plot(X_train, pilih_var_outlier)

NameError: name 'st' is not defined