In [1]:
import pandas as pd

In [2]:
df= pd.read_csv(r"C:\Users\ryana\Downloads\DataSet\apple_5yr_one.csv")

In [3]:
df.head()

,Date,Close,High,Low,Open,Volume
0,NaN,AAPL,AAPL,AAPL,AAPL,AAPL
1,2020-06-04,78.32931518554688,79.1312690763083,77.95506657558614,78.83236263047952,87560400
2,2020-06-05,80.56021881103516,80.62097312386399,78.55046881252456,78.57962969607472,137250400
3,2020-06-08,81.03653717041016,81.07056314819836,79.54441498185327,80.25645380649277,95654400
4,2020-06-09,83.59550476074219,83.98919153470604,80.68416273702039,80.71575616737768,147712400

In [6]:
df=df.iloc[1:].reset_index(drop=True)
df.sample()

,Date,Close,High,Low,Open,Volume
330,2021-09-27,142.47500610351562,143.05326784019874,140.95588573699447,142.57302062293067,74150700

In [7]:
df.isnull().sum()

Date      0
Close     0
High      0
Low       0
Open      0
Volume    0
dtype: int64

In [8]:
df.shape

(1254, 6)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1254 entries, 0 to 1253
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    1254 non-null   datetime64[ns]
 1   Close   1254 non-null   float64
 2   High    1254 non-null   float64
 3   Low     1254 non-null   float64
 4   Open    1254 non-null   float64
 5   Volume  1254 non-null   int64
dtypes: datetime64[ns](1), float64(4), int64(1)
memory usage: 58.9 KB

In [10]:
df['Date'] = pd.to_datetime(df['Date'])

In [12]:
# Convert to Object to Int 

cols=['Close','High','Low','Open','Volume']
for col in cols:
    try:
        df[col] = pd.to_numeric(df[col], errors='coerce')
    except Exception as e:
        print(f"Could not convert column '{col}': {e}")
    else:
        print(f"Column '{col}' converted successfully.")

Column 'Close' converted successfully.
Column 'High' converted successfully.
Column 'Low' converted successfully.
Column 'Open' converted successfully.
Column 'Volume' converted successfully.

In [14]:
df['Date_day']=df['Date'].dt.day
df['Date_month']=df['Date'].dt.month
df['Date_year']=df['Date'].dt.year
df.drop('Date', axis=1,inplace=True)

In [15]:
df.sample(3)

,Close,High,Low,Open,Volume,Date_day,Date_month,Date_year
333,138.682053,141.504703,138.466433,140.799040,89056700,30,9,2021
942,169.098755,171.007227,168.601756,169.734912,95132400,5,3,2024
1199,213.210419,213.669808,209.305536,210.973347,60107600,14,3,2025

##### Split Dataset to Train and Test

In [22]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [16]:
x = df.drop('Close', axis = 1)
y = df['Close']

In [19]:
x.sample()

,High,Low,Open,Volume,Date_day,Date_month,Date_year
404,171.941923,167.662529,169.134802,76138300,11,1,2022

In [20]:
y.sample()

177    126.721451
Name: Close, dtype: float64

In [23]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state=42)

sc=StandardScaler()
x_train_sc=sc.fit_transform(x_train)
x_test_sc=sc.fit_transform(x_test)

In [25]:
from tensorflow.keras.models import Sequential

ModuleNotFoundError: No module named 'tensorflow'

In [24]:
model=Sequential()
model.add(Dense(128, activation='relu', input_dim=7))
model.add(Dropout(0.2))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(1,activation='linear'))
adam=Adam(learning_rate=0.01)

NameError: name 'Sequential' is not defined